// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cloud_logic': 'enable',
    'aws_cloud_logic_custom': [{"id":"lmrobenlz2","name":"Pets","description":"","endpoint":"https://lmrobenlz2.execute-api.us-east-1.amazonaws.com/Development","region":"us-east-1","paths":["/items","/items/123"]}],
    'aws_cognito_identity_pool_id': 'us-east-1:709e3529-9491-4944-9b6c-c83ac3f06a8d',
    'aws_cognito_region': 'us-east-1',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'awsreactivenativeexp-hosting-mobilehub-1535994690',
    'aws_content_delivery_bucket_region': 'us-east-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd2ty9a4ysk9lap.cloudfront.net',
    'aws_dynamodb': 'enable',
    'aws_dynamodb_all_tables_region': 'us-east-1',
    'aws_dynamodb_table_schemas': [{"tableName":"awsreactivenativeexp-mobilehub-1535994690-pets","attributes":[{"name":"userId","type":"S"},{"name":"petId","type":"S"}],"indexes":[],"region":"us-east-1","hashKey":"userId","rangeKey":"petId"}],
    'aws_mobile_analytics_app_id': '6e6e7eff5f494396ac4f3be4b9d8c69f',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '40d353ef-502b-4ba0-a967-94bf9be10df9',
    'aws_project_name': 'aws-reactive-native-ex-pets',
    'aws_project_region': 'us-east-1',
    'aws_resource_bucket_name': 'awsreactivenativeexp-deployments-mobilehub-1535994690',
    'aws_resource_name_prefix': 'awsreactivenativeexp-mobilehub-1535994690',
    'aws_sign_in_enabled': 'enable',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'awsreactivenativeexp-userfiles-mobilehub-1535994690',
    'aws_user_files_s3_bucket_region': 'us-east-1',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'us-east-1_iwob1jsJf',
    'aws_user_pools_mfa_type': 'ON',
    'aws_user_pools_web_client_id': '5ijr0hmhc5bfj3tl18h89k1vrf',
}

export default awsmobile;
